//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveSession
    {
        public int Id { get; set; }
        public string token { get; set; }
        public decimal login { get; set; }
        public System.DateTime InvalidDateTime { get; set; }
    
        public virtual login login1 { get; set; }
    }
}
