//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public login()
        {
            this.ActiveSessions = new HashSet<ActiveSession>();
        }
    
        public decimal Id { get; set; }
        public decimal userNumber { get; set; }
        public string userName { get; set; }
        public string pass { get; set; }
        public string salt { get; set; }
    
        public virtual ICollection<ActiveSession> ActiveSessions { get; set; }
        public virtual user user { get; set; }
    }
}
